### ISSUE TITLE
Wiki: Jarvis

### ISSUE THREAD

**Issue by manparvesh** [swapagarwal/JARVIS-on-Messenger#68] opened 2016-06-07 04:43 UTC
If I type _wiki jarvis_, I should be getting wiki data from the _Jarvis_' page. But it doesn't.
PS: There exists a wiki page for Jarvis.
Screenshot:
![screenshot from 2016-06-07 09-57-58](https://cloud.githubusercontent.com/assets/6629115/15846191/5c9c45d8-2c98-11e6-9ae2-c3179b467729.png)

**Comment by manparvesh** [comment] 2016-06-07 05:03
still not working:
![screenshot from 2016-06-07 10-32-02](https://cloud.githubusercontent.com/assets/6629115/15846491/3c8b3e36-2c9b-11e6-8538-85ae72930d1a.png)

**Comment by swapagarwal** [comment] 2016-06-07 05:03
`wiki jarvis` now triggers the Wikipedia module but searching for Jarvis on wikipedia results in a Disambiguation Error. That'd have to be handled separately!

**Comment by swapagarwal** [comment] 2016-06-07 05:03
https://en.wikipedia.org/wiki/Jarvis

**Comment by manparvesh** [comment] 2016-06-07 05:04
oh okay

**Comment by manparvesh** [comment] 2016-06-07 05:06
Is there something that can be done such that the user gets to choose from the list in case of such errors?

**Comment by swapagarwal** [comment] 2016-06-07 05:09
Do you mean something like the results that are shown in `songs by linkin park`? (Cards)
Or, in one message only?

**Comment by manparvesh** [comment] 2016-06-07 05:14
The cards would be good for detailed information, but then it would open the browser/ Wikipedia app. In that case, inside the message would be better.

**Comment by UshalNaidoo** [comment] 2016-08-10 02:47
I think the problem is that the input has the word "jarvis" in it. This is a bug for any of the searches including 'book jarvis', 'movie jarvis' etc. This is a separate issue from the wiki feature and should be closed.

**Comment by swapagarwal** [comment] 2016-12-10 11:19
Fixed in a3bd4e7af02bb879b6b6b62f1a2de65f79728b33.
User can now choose from search results in case of ambiguity!

**Closed by swapagarwal** 2016-12-10 11:19 UTC
Labels: Bug
